### ISSUE TITLE
Does detectHomebrew support styled-components?

### ISSUE THREAD

**Issue by beamery-tomht** [rangle/radius-tracker#35]
Apologies if this is the wrong place to ask the question and also really great effort writing a static analyser for detecting design system adoption - this is very valuable.

We know a lot of our DS consumers will be using styled-components for their "homebrew" components, as you call them, will radius-tracker be able to work with this? I saw that in your talk it will be focusing on lower-case elements to determine "homebrew".

Another question along a similar line: what about when components are built with other tooling that is not the design system you are measuring adoption for?

**Comment by smoogly** [comment]
> Will radius-tracker be able to work with [styled-components]?

Good question. At the moment, styled components won't be detected. You can see a range of things detected as homebrew in tests: https://github.com/rangle/radius-tracker/blob/fb8287c17011c1f10849e8c44252b23e6c197870/src/lib/detectHomebrew/detectHomebrew.spec.ts

CSS-in-JS libs tend to create component via function calls or tagged literals — those are easy enough to find for specific css-in-js lib, the problem is with number varieties of those libs.

If you have a project using styled components or similar that you want to analyze right now, your best bet is using the tool programmatically, instead of CLI. That way you can use [`filterImports`](https://github.com/rangle/radius-tracker/blob/fb8287c17011c1f10849e8c44252b23e6c197870/src/lib/resolveDependencies/resolveDependencies.ts#L166) from `resolveDependencies` to find imports from the styled components, and then track usages of those imports.

Long term, a plugin system could work for CSS-in-JS libs.


> what about when components are built with other tooling that is not the design system you are measuring adoption for?

I'm not sure I understand the question. Could you elaborate?

**Comment by beamery-tomht** [comment]
Thanks the answer! The tests file makes your current coverage very clear ^_^

> That way you can use [filterImports](https://github.com/rangle/radius-tracker/blob/fb8287c17011c1f10849e8c44252b23e6c197870/src/lib/resolveDependencies/resolveDependencies.ts#L166) from resolveDependencies to find imports from the styled components, and then track usages of those imports.

Okay, thanks for the headsup on this approach!

> I'm not sure I understand the question. Could you elaborate?

Sure! However you already answered the question with the link to tests.

But for clarity - I was wondering that if a file has the following code, would it be able to determine these homebrew cases:

```tsx
import { Button } from 'my-design-system' // all good
import { Select } from 'legacy-internal-component-library' // can this be detected as "homebrew"
import { Filter } from 'chakra-or-something' // also this
```

As these would also be rendered as capitalised custom elements 

> Long term, a plugin system could work for CSS-in-JS libs.

I think a plugin system would be beneficial for many use-cases of determining both homebrew and adoption

**Comment by smoogly** [comment]
It's only been a year!

There's no support for styled components for the purpose of homebrew detection. E.g. in the code below `Component` is now detected as homebrew, because it directly outputs a DOM element.
```
import styled from "styled-components"
const Div = styled.div`background: red`
const Component = () => <Div>Hello, World!</Div>
```

On top of that, tracker supports detection of multiple targets for a while, so imports from multiple component libraries can be tracked separately. See "Multi-target configuration" in the config docs: https://rangle.github.io/radius-tracker/configuration_file#multi-target-configuration

This covers the use case you brought up earlier:
> I was wondering that if a file has the following code, would it be able to determine these homebrew cases:
> ```
> import { Button } from 'my-design-system' // all good
> import { Select } from 'legacy-internal-component-library' // can this be detected as "homebrew"
> import { Filter } from 'chakra-or-something' // also this
> ```

Let me know if you'd like help setting up the tracker, I'm happy to jump on a call and guide you through configuration steps.

**Comment by BerenikaKotelko** [comment]
Hiya! Just as a follow-up to @beamery-tomht, what we'd like to do is check multiple repos with the report generation script, and we wondered about a way to convert the SQLite data into JSON, if possible. Any tips/advice on that?

**Comment by BerenikaKotelko** [comment]
@smoogly we've chatted about it and have a few concerns - I think I haven't communicated our needs well enough. It'd be easier over a call I think, if you're still willing to do that - which timezone are you based in?

**Comment by smoogly** [comment]
I am still happy to help! I've reached out on LinkedIn, but also feel free to drop me a message at `arseny.smoogly@rangle.io` — let's find a good time for a call.
